# Generated by Django 2.0.5 on 2018-08-28 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complains',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('title', models.TextField(db_column='title', max_length=200)),
                ('text', models.TextField(db_column='text', max_length=1000)),
                ('image', models.TextField(db_column='image', max_length=500000)),
                ('location', models.TextField(db_column='location', max_length=100)),
                ('compl_by', models.TextField(db_column='user', max_length=50)),
                ('status', models.TextField(db_column='status', max_length=200)),
                ('results', models.TextField(db_column='results', max_length=1000)),
            ],
            options={
                'db_table': 'Complaints',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('emp_id', models.TextField(db_column='emp_id', max_length=10)),
                ('emp_name', models.TextField(db_column='emp_name', max_length=100)),
                ('creds', models.TextField(db_column='credentials', max_length=50)),
                ('desg', models.TextField(db_column='designation', max_length=20)),
            ],
            options={
                'db_table': 'Employee Details',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('uid', models.TextField(db_column='User ID', max_length=50)),
                ('creds', models.TextField(db_column='credentials', max_length=50)),
            ],
            options={
                'db_table': 'Users',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('worker_id', models.TextField(db_column='emp_id', max_length=10)),
                ('worker_name', models.TextField(db_column='emp_name', max_length=100)),
                ('mobile', models.IntegerField(db_column='mobile no.')),
                ('desg', models.TextField(db_column='designation', max_length=20)),
                ('status', models.TextField(db_column='status', max_length=20)),
                ('assigned_by', models.ForeignKey(db_column='empId', on_delete=django.db.models.deletion.CASCADE, to='project.Employee')),
            ],
            options={
                'db_table': 'Worker Details',
                'managed': True,
            },
        ),
    ]
