# Generated by Django 2.0.7 on 2018-08-18 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complains',
            name='image',
            field=models.TextField(db_column='image', max_length=50000),
        ),
    ]
