# Generated by Django 2.0.7 on 2018-08-18 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20180818_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complains',
            name='image',
            field=models.TextField(db_column='image', max_length=500000),
        ),
    ]
